baseURL = "https://bowser1704.github.io/"
googleAnalytics = "UA-151172261-1"
languageCode = "zh-hans"
title = "Bowser's blog"
theme = "hermit"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
enableRobotsTXT = true
hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 5  # Maximum number of items in the RSS feed.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
defaultContentDir = "posts"

[author]
  name = "Bowser"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags"

[params]
  gitUrl = "https://github.com/Bowser1704/bowser1704.github.io/commit/"

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "Echoes from distant lands"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "email"
    url = "mailto:bowser1704@gmail.com"
  
  [[params.social]]
    name = "telegram"
    url = "https://t.me/bowser1704"
  
  [[params.social]]
    name = "github"
    url = "https://github.com/Bowser1704"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
  
  # [[menu.main]]
  #   name = "Notes"
  #   url = "notes/"
  #   weight = 20

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 30
